import { useState } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { submitDiagnosis } from '../../api/diagnosis';
import { ApiError } from '../../api/errors';
import { colors, radius, spacing } from '../../theme';

type Turn = { question: string; answer?: string; error?: string };
export function AssistantConversation({ question, answer, onNew }: { question: string; answer: string; onNew: () => void }) {
  const [turns, setTurns] = useState<Turn[]>([{ question, answer }]); const [text, setText] = useState(''); const [busy, setBusy] = useState(false);
  async function send() { const next = text.trim(); if (!next || busy) return; setText(''); setBusy(true); setTurns(value => [...value, { question: next }]); try { const result = await submitDiagnosis({ text: next }); setTurns(value => value.map((turn, index) => index === value.length - 1 ? { ...turn, answer: result.answer || 'Chưa có nội dung trả lời.' } : turn)); } catch (value) { const error = value instanceof ApiError ? value.userMessage : 'Chưa thể trả lời lúc này. Vui lòng thử lại sau.'; setTurns(items => items.map((turn, index) => index === items.length - 1 ? { ...turn, error } : turn)); } finally { setBusy(false); } }
  return <View style={styles.wrap} testID="assistant-conversation"><View style={styles.heading}><View style={styles.icon}><Ionicons name="chatbubbles-outline" size={22} color={colors.primary} /></View><View><Text style={styles.title}>Trợ lý MaiCare</Text><Text style={styles.subtitle}>Trợ lý chăm sóc mai vàng</Text></View></View>{turns.map((turn, index) => <View key={`${turn.question}-${index}`} style={styles.turn}><View style={styles.user}><Text style={styles.userText}>{turn.question}</Text></View>{turn.answer && <View style={styles.assistant}><Text style={styles.assistantLabel}>MaiCare</Text><Text style={styles.answer}>{turn.answer}</Text></View>}{turn.error && <Text accessibilityRole="alert" style={styles.error}>{turn.error}</Text>}</View>)}{busy && <View style={styles.loading}><ActivityIndicator color={colors.primary} /><Text style={styles.loadingText}>Đang tìm câu trả lời...</Text></View>}<View style={styles.composer}><TextInput accessibilityLabel="Câu hỏi cho MaiCare" value={text} onChangeText={setText} multiline placeholder="Hỏi thêm về cách chăm sóc mai..." placeholderTextColor={colors.muted} style={styles.input} /><Pressable accessibilityRole="button" accessibilityLabel="Gửi câu hỏi" disabled={!text.trim() || busy} onPress={() => void send()} style={[styles.send, (!text.trim() || busy) && styles.disabled]}><Ionicons name="send" size={19} color="#fff" /></Pressable></View><Pressable accessibilityRole="button" onPress={onNew} style={styles.new}><Text style={styles.newText}>Trở về kiểm tra tình trạng mai</Text></Pressable></View>;
}
const styles = StyleSheet.create({ wrap: { gap: spacing.md }, heading: { flexDirection: 'row', alignItems: 'center', gap: 10 }, icon: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, title: { color: colors.primaryDark, fontSize: 21, fontWeight: '900' }, subtitle: { color: colors.muted, fontSize: 12, marginTop: 2 }, turn: { gap: 9 }, user: { alignSelf: 'flex-end', maxWidth: '86%', padding: 12, borderRadius: radius.lg, borderBottomRightRadius: 5, backgroundColor: colors.primary }, userText: { color: '#fff', lineHeight: 21 }, assistant: { alignSelf: 'flex-start', maxWidth: '94%', padding: 14, borderRadius: radius.lg, borderBottomLeftRadius: 5, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, gap: 5 }, assistantLabel: { color: colors.primary, fontSize: 12, fontWeight: '900' }, answer: { color: colors.text, lineHeight: 23 }, error: { color: colors.danger, backgroundColor: colors.dangerSoft, padding: 11, borderRadius: radius.md }, loading: { flexDirection: 'row', alignItems: 'center', gap: 8 }, loadingText: { color: colors.muted }, composer: { flexDirection: 'row', alignItems: 'flex-end', gap: 8, paddingTop: 4 }, input: { flex: 1, minHeight: 48, maxHeight: 112, padding: 12, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surface, color: colors.text }, send: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, disabled: { opacity: .45 }, new: { minHeight: 46, alignItems: 'center', justifyContent: 'center' }, newText: { color: colors.primary, fontWeight: '800' } });
