import { expect, test } from '@playwright/test';
import path from 'node:path';

test('MaiCare real auth, tutorial, diagnosis states, responsive shell and logout', async ({ page }) => {
  const suffix = Date.now(); const username = `edge_${suffix}`; const password = `MaiCare!${suffix}`; const email = `${username}@local.test`;
  const consoleErrors: string[] = []; const pageErrors: string[] = []; const failedRequests: string[] = []; const apiResponses: string[] = [];
  page.on('console', message => { if (message.type() === 'error') consoleErrors.push(message.text()); });
  page.on('pageerror', error => pageErrors.push(error.message));
  page.on('requestfailed', request => failedRequests.push(`${request.method()} ${request.url()} ${request.failure()?.errorText}`));
  page.on('response', response => { if (response.url().includes('/api/v1/user/')) apiResponses.push(`${response.request().method()} ${response.status()} ${new URL(response.url()).pathname}`); });

  await page.goto('/'); await page.evaluate(() => localStorage.removeItem('maicare_tutorial_v1_completed'));
  await expect(page).toHaveTitle('MaiCare – Trợ lý chăm sóc mai vàng'); await expect(page.getByTestId('login-screen')).toBeVisible(); await expect(page.getByText('MaiCare', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: /Đăng ký/ }).click(); await page.getByLabel('Họ và tên').fill('Người dùng Edge'); await page.getByLabel('Email').fill(email); await page.getByTestId('register-username').fill(username); await page.getByTestId('register-password').fill(password); await page.getByTestId('register-confirm').fill(password); await page.getByTestId('register-submit').click();
  await expect(page.getByText('Đăng ký thành công. Hãy đăng nhập để tiếp tục.')).toBeVisible(); await page.getByTestId('login-password').last().fill(password); await page.getByTestId('login-submit').last().click();

  const tutorial = page.getByTestId('tutorial-overlay'); await expect(tutorial.getByText('Chào mừng bạn đến với MaiCare')).toBeVisible(); await tutorial.getByTestId('tutorial-next').click(); await expect(tutorial.getByText('Thêm ảnh lá mai', { exact: true })).toBeVisible(); const targetBox = await page.getByTestId('tutorial-target-image').boundingBox(); const focusBox = await page.getByTestId('tutorial-focus').boundingBox(); expect(Math.abs((targetBox?.x || 0) - (focusBox?.x || 0))).toBeLessThanOrEqual(10); expect(Math.abs((targetBox?.y || 0) - (focusBox?.y || 0))).toBeLessThanOrEqual(10); await page.screenshot({ path: 'artifacts/e2e/tutorial-390x844.png' }); await tutorial.getByRole('button', { name: 'Quay lại' }).click(); await expect(tutorial.getByText('Chào mừng bạn đến với MaiCare')).toBeVisible(); await tutorial.getByRole('button', { name: 'Bỏ qua' }).click(); await expect(tutorial).not.toBeVisible(); await expect.poll(() => page.evaluate(() => localStorage.getItem('maicare_tutorial_v1_completed'))).toBe('true');
  await page.reload(); await expect(page.getByTestId('diagnosis-screen')).toBeVisible(); await expect(tutorial).not.toBeVisible();

  const submit = page.getByTestId('diagnosis-submit'); await expect(submit).toBeDisabled(); await page.getByTestId('add-image-card').click(); await expect(page.getByText('Thêm ảnh', { exact: true }).last()).toBeVisible(); await expect(page.getByText('Dùng camera để chụp ảnh mới')).toBeVisible(); await page.getByText('Hủy', { exact: true }).click();
  await page.getByTestId('diagnosis-description').fill('Lá mai có đốm nâu, tôi nên làm gì?'); await expect(submit).toBeEnabled(); await expect(page.getByText(/Bạn đang hỏi thông tin chung/)).toBeVisible(); await expect(submit).toContainText('Hỏi MaiCare'); await submit.click(); await expect(page.getByText('Tính năng này chưa sẵn sàng. Vui lòng thử lại sau.')).toBeVisible();

  const sampleImage = path.resolve(process.cwd(), '..', '..', 'chat_bot_maivang-backend', 'diseases', '20260124_151321.jpg');
  await page.getByTestId('add-image-card').click(); const chooser = page.waitForEvent('filechooser'); await page.getByTestId('library-option').click(); await (await chooser).setFiles(sampleImage); await expect(page.getByTestId('selected-image-card')).toBeVisible(); await expect(page.getByText('Ảnh đã chọn')).toBeVisible(); await expect(submit).toContainText('Kiểm tra ảnh'); await expect(submit).toBeEnabled();
  await page.getByTestId('diagnosis-description').fill(''); await submit.click(); await expect(page.getByText('Tính năng này chưa sẵn sàng. Vui lòng thử lại sau.')).toBeVisible();
  await page.getByText('Thay ảnh').click(); const replacement = page.waitForEvent('filechooser'); await page.getByTestId('library-option').click(); await (await replacement).setFiles(sampleImage); await page.getByTestId('remove-image').click(); await expect(page.getByTestId('add-image-card')).toBeVisible();

  await page.evaluate(() => Object.defineProperty(navigator, 'mediaDevices', { value: undefined, configurable: true })); await page.getByTestId('add-image-card').click(); await page.getByTestId('camera-option').click(); await expect(page.getByText('Không tìm thấy camera trên thiết bị này.')).toBeVisible(); await expect(page.getByRole('button', { name: 'Chọn ảnh từ thư viện' })).toBeVisible(); await page.getByRole('button', { name: 'Đóng camera' }).click(); await expect(page.getByText('Không tìm thấy camera trên thiết bị này.')).not.toBeVisible(); await page.getByTestId('diagnosis-description').fill('');

  for (const viewport of [{ width: 320, height: 568 }, { width: 375, height: 812 }, { width: 390, height: 844 }, { width: 430, height: 932 }, { width: 1280, height: 800 }]) { await page.setViewportSize(viewport); const bodyWidth = await page.locator('body').evaluate(node => node.scrollWidth); expect(bodyWidth).toBeLessThanOrEqual(viewport.width); await page.screenshot({ path: `artifacts/e2e/maicare-${viewport.width}x${viewport.height}.png` }); }
  expect(await page.getByTestId('app-shell').evaluate(node => node.getBoundingClientRect().width)).toBeLessThanOrEqual(460);

  await page.getByText('Lịch sử', { exact: true }).last().click(); await expect(page.getByText('Chưa có lịch sử để hiển thị')).toBeVisible(); await page.getByText('Tài khoản', { exact: true }).last().click(); await expect(page.getByTestId('account-screen')).toBeVisible();
  await page.setViewportSize({ width: 320, height: 568 }); await page.getByTestId('replay-tutorial').click(); await expect(tutorial.getByText('Chào mừng bạn đến với MaiCare')).toBeVisible(); for (let step = 0; step < 6; step++) { const box = await tutorial.getByTestId('tutorial-tooltip').boundingBox(); if (box) { expect(box.y).toBeGreaterThanOrEqual(0); expect(box.y + box.height).toBeLessThanOrEqual((page.viewportSize()?.height || 800) + 1); } await tutorial.getByTestId('tutorial-next').click(); } await expect(tutorial).not.toBeVisible();
  await page.getByText('Tài khoản', { exact: true }).last().click(); await page.getByTestId('logout-button').click(); await expect(page.getByTestId('login-screen')).toBeVisible(); await page.getByTestId('login-username').last().fill(username); await page.getByTestId('login-password').last().fill(password); await page.getByTestId('login-submit').last().click(); await expect(tutorial).not.toBeVisible(); await page.getByText('Tài khoản', { exact: true }).last().click(); await page.getByTestId('delete-account-button').click(); await page.getByTestId('confirm-delete').click(); await expect(page.getByText('Tài khoản đã được xóa.')).toBeVisible();

  expect(apiResponses).toContain('POST 201 /api/v1/user/register/'); expect(apiResponses.filter(item => item === 'POST 200 /api/v1/user/login/').length).toBeGreaterThanOrEqual(2); expect(apiResponses.filter(item => item === 'GET 200 /api/v1/user/me/').length).toBeGreaterThanOrEqual(2); expect(apiResponses).toContain('POST 200 /api/v1/user/logout/'); expect(apiResponses).toContain('DELETE 204 /api/v1/user/me/');
  expect(consoleErrors).toEqual([]); expect(pageErrors).toEqual([]); expect(failedRequests).toEqual([]);
});
